# Software_Engineering
#Базовые операции языка Python
Отчет по Теме выполнил:
- Феденёв Алексей Сергеевич
- ИНО ОЗБ ПОАС-22-2

| Задание | Сам_раб |
| ------ | ------ |
| Задание 1 | + |
| Задание 2 | + | 
| Задание 3 | + |
| Задание 4 | + |
| Задание 5 | + |

знак "+" - задание выполнено; знак "-" - задание не выполнено;

Работу проверили: Панов Михаил Александрович
(и.о. заведующего кафедрой информационных технологий и статистики,
кандидат экономических наук, доцент.)

## Самостоятельная работа №10
## Задание 1.
###   Вовочка решил заняться спортивным программированием на python, но для этого он должен знать за какое время выполняется его программа. Он решил, что для этого ему идеально подойдет декоратор для функции, который будет выяснять за какое время выполняется та или иная функция. Помогите Вовочке в его начинаниях и напишите такой декоратор.

```python
import time
def e_time(function):
    def wrapper():
        start_time = time.time() #время начала выполнения функции
        function() #запускаем функцию
        end_time = time.time() #время окончания выполнения функции
        result = end_time - start_time #время выполнения
        print(f'Время выполнения функции: {result} секунд')
    return wrapper()

@e_time #декоратор
def fibonacci():
    fib1 = fib2 = 1

    for i in range(2, 200):
        fib1, fib2 = fib2, fib1 + fib2
        print(fib2, end='')

if __name__ == '__main__':
    fibonacci()
```
### Результат
![Меню](https://github.com/AlekseyFedenev/Software_Engineering/blob/Tema10/pic/tema101.png)
### Вывод: с помощью декоратора можно добавить дополнительное поведение к функции, не изменяя ее саму. В данном случае мы используем декоратор для измерения времени выполнения функции Fibonacci()

## Задание 2.
###  Посмотрев на Вовочку, вы также загорелись идеей спортивного программирования, начав тренировки вы узнали, что для решения некоторых задач необходимо считывать данные из файлов. Но через некоторое время вы столкнулись с проблемой что файлы бывают пустыми, и вы не получаете вводные данные для решения задачи. После этого вы решили не просто считывать данные из файла, а всю конструкцию оборачивать в исключения, чтобы избежать такой проблемы. Создайте пустой файл и файл, в котором есть какая-то информация. Напишите код программы. Если файл пустой, то, нужно вызвать исключение (“бросить исключение”) и вывести в консоль “файл пустой”, а если он не пустой, то вывести информацию из файла

```python
def check_file(file_name):
    try: #начала блока обработки исключений
        with open(file_name, 'r') as file: #открытие файла для чтения
            contents = file.read() #чтение содержимого файла
            if not contents:  # Если файл пустой
                raise Exception("Файл пустой")
            else:  # Если в файле есть информация
                print(contents)
    except FileNotFoundError: #обработка исключения
        print("Файл не найден")
    except Exception as e: #обработка исключения
        print(e)

# Проверка пустого файла
print("Содержимое не пустого файла:")
check_file('one')

# Проверка непустого файла
print("\nСодержимое пустого файла:")
check_file('two')
```
### Результат
![Меню](https://github.com/AlekseyFedenev/Software_Engineering/blob/Tema10/pic/tema102.png)
### Вывод: с помощью исключений можно обрабатывать возникающие ошибки и контролировать ход выполнения программы. В данной программе используются исключения для проверки содержимого в файлах

## Задание 3.
###  Напишите функцию, которая будет складывать 2 и введенное пользователем число, но если пользователь введет строку или другой неподходящий тип данных, то в консоль выведется ошибка “Неподходящий тип данных. Ожидалось число.”. Реализовать функционал программы необходимо через try/except и подобрать правильный тип исключения. Создавать собственное исключение нельзя. Проведите несколько тестов, в которых исключение вызывается и нет.

```python
def two_numbers():
    try:  # Начало блока обработки исключений
        user_input = input("Введите число: ")
        number = float(user_input)  # Преобразование введенной строки в число типа float
        result = 2 + number  # Сложение 2 и введенного числа
        print(f"Результат сложения: {result}")

    except ValueError:  # Обработка исключения
        print("Неподходящий тип данных. Ожидалось число")

two_numbers()  #Вызов функции
```
### Результат
![Меню](https://github.com/AlekseyFedenev/Software_Engineering/blob/Tema10/pic/tema103.png)
![Меню](https://github.com/AlekseyFedenev/Software_Engineering/blob/Tema10/pic/tema1031.png)

## Задание 4.
###  Создайте собственный декоратор, который будет использоваться для двух любых вами придуманных функций. Декораторы, которые использовались ранее в работе нельзя воссоздавать. Результатом выполнения задачи будет: класс декоратора, две как-то связанными с ним функциями, скриншот консоли с выполненной программой и подробные комментарии, которые будут описывать работу вашего кода

```python
class Rectangle: #определение класса
    def __init__(self, a, b): #метод инициализации
        self.a = a #инициализзация атрибута
        self.b = b #инициализация атрибута

    @property #декоратор
    def area(self): #метод для вычисления площади
        return self.a * self.b #результат умножения

rect = Rectangle(15, 5) #создание объекта класса Rectangle с параметрами
print(rect.area) #вывод на экран значения
```
### Результат
![Меню](https://github.com/AlekseyFedenev/Software_Engineering/blob/Tema10/pic/tema104.png)

## Задание 5.
### Создайте собственное исключение, которое будет использоваться в двух любых фрагментах кода. Исключения, которые использовались ранее в работе нельзя воссоздавать. Результатом выполнения задачи будет: класс исключения, код к котором в двух местах используется это исключение, скриншот консоли с выполненной программой и подробные комментарии, которые будут описывать работу вашего кода

```python
class DivisionError(Exception): #определение класса
    def __init__(self, number, divisor): #метод инициализация
        self.message = f"Число {number} не делится на {divisor}" #сообщение об ошибке
        super().__init__(self.message) #вызов конструктора класса Exception

def divide_number(number, divisor): #метод игициализации
    if number % divisor != 0: #проверяем, делится ли число без остатка
        raise DivisionError(number, divisor) #если нет, то исключение
    return number / divisor #иначе результат

try:
    result = divide_number(10, 5) #выполняем деление
    print(f"Результат деления: {result}") #выводим результат, если успешно
except DivisionError as e:  #исключение
    print(f"Ошибка деления: {e.message}") #выводим об ошибке
```
### Результат
![Меню](https://github.com/AlekseyFedenev/Software_Engineering/blob/Tema10/pic/tema105.png)
